import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from 'flowbite-react'
import { useState } from 'react'
import LoginModal from '../components/LoginModal'
import { db } from '../utils/firebase-config'
import { doc, getDoc } from 'firebase/firestore'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  const [showLoginModal, setShowLoginModal] = useState(false)
  const [loggedIn, setLoggedIn] = useState(false)
  const [hostName, setHostName] = useState("")
  const [hostEmail, setHostEmail] = useState("")

  const onLoginClose = () => {
    setShowLoginModal(false)
  }

  const onLoginSubmit = async (email) => {
    const hostRef = doc(db, "hosts", email)
    const hostSnap = await getDoc(hostRef)

    if (hostSnap.exists()) {
      setHostEmail(hostSnap.id)
      setHostName(hostSnap.data().name)
      setLoggedIn(true)
      setShowLoginModal(false)
    } else {
      alert(
        "Whoops! Looks like your not a host yet. Contact support to setup an account."
      )
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2eVG5g0fw57MqQ7hgVoqEAs9yED1j1Mg&libraries=places" async defer />
        <Script src="https://cdn.jsdelivr.net/npm/add-to-calendar-button" async defer />
        { hostName.length > 0 ? <p className="mb-5">{`Welcome, ${hostName}! Let's create a new event.`}</p> : <></>}
        {loggedIn ? <Button><Link href={{pathname: '/create-event'}}>Create New Event</Link></Button> : <Button onClick={() => { setShowLoginModal(true) }}>Login to Superhost</Button>}
        <LoginModal showModal={showLoginModal} onModalClose={onLoginClose} onLoginSubmit={onLoginSubmit} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
